name: Docker image poke-view CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      pkg-name: ${{ steps.pkg.outputs.name }}
      pkg-version: ${{ steps.pkg.outputs.version }}

    steps:
      # 1. Clona tu repositorio en la máquina virtual
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Detectar cambios que requieren nueva imagen
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            build_image:
              - 'src/**'
              - 'public/**'
              - 'Dockerfile'
              - 'package.json'
              - 'package-lock.json'
              - 'angular.json'
              - 'docker-entrypoint.sh'
              - 'tsconfig.json'
              - 'tsconfig.app.json'
              - 'tsconfig.spec.json'

      - name: Mostrar decisión de build
        run: echo "¿Construir imagen? -> ${{ steps.changes.outputs.build_image }}"

      - name: Read metadata from package.json
        id: pkg
        run: |
          echo "name=$(jq -r .name package.json)" >> $GITHUB_OUTPUT
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: steps.changes.outputs.build_image == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Extract metadata for Docker
        if: steps.changes.outputs.build_image == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME  }}/${{ steps.pkg.outputs.name }}
          tags: |
              type=raw,value=${{ steps.pkg.outputs.version }}
              type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build Docker image
        if: steps.changes.outputs.build_image == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  
  deploy:
    needs: build
    uses: forcet/devop-template/.github/workflows/docker-image-devop-template.yml@main
    with:
      helm_name: helm-template
      helm_release: forcet-poke-view
      helm_version: 8
      image_repository: ${{ needs.build.outputs.pkg-name }}
      image_tag: ${{ needs.build.outputs.pkg-version }}
      namespace: forcet22-dev
    secrets: inherit